/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_21130876_proyecto_01;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 * Instituto Tecnológico de la Laguna
 * Programación orientada a objetos
 * PROYECTO 01
 * Autor: Luis Ernesto Barranco Núñez
 * 2do Semestre
 */
public class PB_21130876_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_21130876_Frame_01
     */

    public PB_21130876_Frame_01() {
        initComponents();
        jTable_inversiones.setShowGrid(true);
        jTable_totales.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_inversiones = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_totales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_calcular = new javax.swing.JButton();
        jButton_aleatorio = new javax.swing.JButton();
        jButton_borrar = new javax.swing.JButton();
        jButton_ejemplo = new javax.swing.JButton();
        jButton_orden_alfabetico = new javax.swing.JButton();
        jButton_orden_tasa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_mayor_menor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner_inversiones = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_mayor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_menor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PB_Proyecto_01_Luis Barranco_Inversiones");
        setPreferredSize(new java.awt.Dimension(810, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(810, 620));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Luis Ernesto Barranco Núñez \nNúm. de control: 21130876 \nProyecto 01 \n2do Semestre \nAplicación para calcular la tasa de interes\ncompuesto en base al capital inicial, final \ny al periodo de tiempo.");
        jScrollPane1.setViewportView(jTextArea1);

        jTable_inversiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Capital inicial", "Periodo", "Tasa de interés", "Intereses generados", "Capital final"
            }
        ));
        jScrollPane3.setViewportView(jTable_inversiones);
        if (jTable_inversiones.getColumnModel().getColumnCount() > 0) {
            jTable_inversiones.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable_inversiones.getColumnModel().getColumn(1).setPreferredWidth(45);
            jTable_inversiones.getColumnModel().getColumn(2).setPreferredWidth(35);
            jTable_inversiones.getColumnModel().getColumn(3).setPreferredWidth(45);
            jTable_inversiones.getColumnModel().getColumn(5).setPreferredWidth(45);
        }

        jTable_totales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Capital inicial", "Periodo", "Tasa de interés", "Intereses generados", "Capital final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_totales);
        if (jTable_totales.getColumnModel().getColumnCount() > 0) {
            jTable_totales.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable_totales.getColumnModel().getColumn(1).setPreferredWidth(45);
            jTable_totales.getColumnModel().getColumn(2).setPreferredWidth(35);
            jTable_totales.getColumnModel().getColumn(3).setPreferredWidth(45);
            jTable_totales.getColumnModel().getColumn(5).setPreferredWidth(45);
        }

        jLabel1.setText("Totales");

        jButton_calcular.setText("Calcular");
        jButton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularActionPerformed(evt);
            }
        });

        jButton_aleatorio.setText("Aleatorios");
        jButton_aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aleatorioActionPerformed(evt);
            }
        });

        jButton_borrar.setText("Borrar");
        jButton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarActionPerformed(evt);
            }
        });

        jButton_ejemplo.setText("Ejemplo");
        jButton_ejemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ejemploActionPerformed(evt);
            }
        });

        jButton_orden_alfabetico.setText("Orden Alfabetico por nombre");
        jButton_orden_alfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orden_alfabeticoActionPerformed(evt);
            }
        });

        jButton_orden_tasa.setText("Orden Descendente por tasa de interés");
        jButton_orden_tasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orden_tasaActionPerformed(evt);
            }
        });

        jLabel3.setText("Datos de las inversiones");

        jButton_mayor_menor.setText("Mayor y menor tasa de interés");
        jButton_mayor_menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mayor_menorActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_21130876_proyecto_01/PB_21130876_asignacion_01a.jpeg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_21130876_proyecto_01/PB_21130876_asignacion_01b.jpg"))); // NOI18N

        jSpinner_inversiones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_inversionesStateChanged(evt);
            }
        });

        jLabel5.setText("Número de inversiones:");

        jLabel6.setText("Mayor:");

        jLabel_mayor.setBackground(new java.awt.Color(153, 255, 153));
        jLabel_mayor.setOpaque(true);

        jLabel8.setText("Menor:");

        jLabel_menor.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_menor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_ejemplo)
                            .addComponent(jButton_borrar)
                            .addComponent(jButton_calcular)
                            .addComponent(jButton_aleatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_mayor_menor)
                            .addComponent(jButton_orden_tasa)
                            .addComponent(jButton_orden_alfabetico)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner_inversiones, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_mayor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel_menor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_inversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_calcular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_borrar)
                                .addComponent(jButton_mayor_menor))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_ejemplo)
                                .addComponent(jButton_orden_alfabetico))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_aleatorio)
                                .addComponent(jButton_orden_tasa)))))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_mayor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_menor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner_inversionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_inversionesStateChanged
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel)jTable_inversiones.getModel();
        
        modelo.setRowCount((int)jSpinner_inversiones.getValue());
    }//GEN-LAST:event_jSpinner_inversionesStateChanged

    private void jButton_aleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aleatorioActionPerformed
        // TODO add your handling code here:
        
        Random azar = new Random();
        for(int r=0; r < jTable_inversiones.getRowCount(); r++)
        {
            jTable_inversiones.setValueAt(Nombres.nextNombreCompleto(), r, 0); // Nombre
            jTable_inversiones.setValueAt(azar.nextInt(25000), r, 1); // Capital inicial
            jTable_inversiones.setValueAt(azar.nextInt(15)+1, r, 2); // periodo de tiempo
            jTable_inversiones.setValueAt(20000+azar.nextInt(7000), r, 5); // Capital final
            
            
            //borrar tasa e intereses previos
            jTable_inversiones.setValueAt("",r,3);//tasa de interés
            jTable_inversiones.setValueAt("",r,4);//intereses generados
        }
        //borrar totales previos
        jTable_totales.setValueAt(null,0,0);//Nombre
        jTable_totales.setValueAt("",0,1);//Capital inicial
        jTable_totales.setValueAt("",0,2);//Periodo
        jTable_totales.setValueAt("",0,3);//tasa de interés
        jTable_totales.setValueAt("",0,4);//intereses generados
        jTable_totales.setValueAt("",0,5);//Capital final
        
    }//GEN-LAST:event_jButton_aleatorioActionPerformed

    private void jButton_ejemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ejemploActionPerformed
        // TODO add your handling code here:
        jSpinner_inversiones.setValue(4);
        //primer renglón
        jTable_inversiones.setValueAt("Pedro Robles",0,0);//Nombre
        jTable_inversiones.setValueAt("50000",0,1);//Capital inicial
        jTable_inversiones.setValueAt("71105.03",0,5);//Capital final
        jTable_inversiones.setValueAt("8",0,2);//Periodo
        //primer renglón
        jTable_inversiones.setValueAt("Lucía Quirarte",1,0);//Nombre
        jTable_inversiones.setValueAt("210000",1,1);//Capital inicial
        jTable_inversiones.setValueAt("335099.25",1,5);//Capital final
        jTable_inversiones.setValueAt("6",1,2);//Periodo
        //primer renglón
        jTable_inversiones.setValueAt("Rebeca Jiménez",2,0);//Nombre
        jTable_inversiones.setValueAt("300000",2,1);//Capital inicial
        jTable_inversiones.setValueAt("938518.69",2,5);//Capital final
        jTable_inversiones.setValueAt("15",2,2);//Periodo
        //primer renglón
        jTable_inversiones.setValueAt("Ariel Martínez",3,0);//Nombre
        jTable_inversiones.setValueAt("125000",3,1);//Capital inicial
        jTable_inversiones.setValueAt("232300.67",3,5);//Capital final
        jTable_inversiones.setValueAt("12",3,2);//Periodo
        //borrar tasa e intereses previos
        for(int r  = 0; r<jTable_inversiones.getRowCount();r++){
            jTable_inversiones.setValueAt("",r,3);//tasa de interés
            jTable_inversiones.setValueAt("",r,4);//intereses generados
        }
        //borrar totales previos
        jTable_totales.setValueAt(null,0,0);//Nombre
        jTable_totales.setValueAt("",0,1);//Capital inicial
        jTable_totales.setValueAt("",0,2);//Periodo
        jTable_totales.setValueAt("",0,3);//tasa de interés
        jTable_totales.setValueAt("",0,4);//intereses generados
        jTable_totales.setValueAt("",0,5);//Capital final
    }//GEN-LAST:event_jButton_ejemploActionPerformed

    private void jButton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarActionPerformed
        // TODO add your handling code here:
        //borramos los datos
        for(int r = 0; r<jTable_inversiones.getRowCount();r++){
            jTable_inversiones.setValueAt(null,r,0);//Nombre
            jTable_inversiones.setValueAt("",r,1);//Capital inicial
            jTable_inversiones.setValueAt("",r,2);//periodo
            jTable_inversiones.setValueAt("",r,3);//tasa de interés
            jTable_inversiones.setValueAt("",r,4);//intereses generados
            jTable_inversiones.setValueAt("",r,5);//Capital final
        }    
            
            jTable_totales.setValueAt(null,0,0);//Nombre
            jTable_totales.setValueAt("",0,1);//Capital inicial
            jTable_totales.setValueAt("",0,2);//Periodo
            jTable_totales.setValueAt("",0,3);//tasa de interés
            jTable_totales.setValueAt("",0,4);//intereses generados
            jTable_totales.setValueAt("",0,5);//Capital final
            
            jLabel_mayor.setText("");
            jLabel_menor.setText("");
    }//GEN-LAST:event_jButton_borrarActionPerformed

    private void jButton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularActionPerformed
        // TODO add your handling code here:
        Inversionistas A = new Inversionistas(jTable_inversiones);
        A.mostrar(jTable_inversiones,jTable_totales);
    }//GEN-LAST:event_jButton_calcularActionPerformed

    private void jButton_mayor_menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mayor_menorActionPerformed
        // TODO add your handling code here:
        Inversionistas B = new Inversionistas(jTable_inversiones);
        
        jLabel_mayor.setText(B.MayorInteres().getInversionista());
        jLabel_menor.setText(B.MenorInteres().getInversionista());
    }//GEN-LAST:event_jButton_mayor_menorActionPerformed

    private void jButton_orden_alfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_orden_alfabeticoActionPerformed
        // TODO add your handling code here:
        Inversionistas C = new Inversionistas(jTable_inversiones);
        //orden A-Z
        C.OrdenAlfabetico();
        C.mostrar(jTable_inversiones, jTable_totales);
    }//GEN-LAST:event_jButton_orden_alfabeticoActionPerformed

    private void jButton_orden_tasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_orden_tasaActionPerformed
        // TODO add your handling code here:
        Inversionistas D = new Inversionistas(jTable_inversiones);
        //orden descendente
        D.OrdenTasaInteres();
        D.mostrar(jTable_inversiones, jTable_totales);
    }//GEN-LAST:event_jButton_orden_tasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_21130876_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_21130876_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_21130876_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_21130876_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_21130876_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aleatorio;
    private javax.swing.JButton jButton_borrar;
    private javax.swing.JButton jButton_calcular;
    private javax.swing.JButton jButton_ejemplo;
    private javax.swing.JButton jButton_mayor_menor;
    private javax.swing.JButton jButton_orden_alfabetico;
    private javax.swing.JButton jButton_orden_tasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_mayor;
    private javax.swing.JLabel jLabel_menor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner_inversiones;
    private javax.swing.JTable jTable_inversiones;
    private javax.swing.JTable jTable_totales;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
